### ISSUE TITLE
Not working with the updated web interface

### ISSUE THREAD

**Issue by jealie** [fsolt/pewdata#3]
Just tried the package today, for the first time, but with no luck so far.

I believe Pew changed their webpage recently: the form now requires a first name, last name, and email.

**Comment by fsolt** [comment]
Yep, the webpage update killed the package--thanks for tipping me off.  I'll have to work on coming up with a new solution.

**Comment by jealie** [comment]
Thanks for the package by the way! I would be happy to test the fix or contribute to it.

Cheers :)

**Comment by fsolt** [comment]
Closed by c1abd4f9755d0818025b89f49bedd078aacabd1f. It's completely rewritten to use RSelenium now; sorry it took so long for me to get to it!
